service: serverlessSetup

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1

# functions
functions:
  hello:
    handler: src/main/hello.handler
    events:
      - http:
          path: serverlessSetup/hello
          method: get
  goodbye:
    handler: src/main/goodbye.handler
    events:
      - http:
          path: serverlessSetup/goodbye
          method: post

# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline









